In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import model_selection, linear_model, metrics

In [2]:
%run utils.ipynb

In [3]:
prediction = pd.read_csv("HS_Karlsruhe_1.csv")

In [4]:
gt = pd.read_csv("../data/DMC-2019-realclass.csv")
np.array(gt)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [5]:
confusion_matrix = metrics.confusion_matrix(np.array(gt), np.array(prediction))
dmc_score = np.sum(confusion_matrix * np.array([[0, -25], [-5, 5]]))

In [6]:
confusion_matrix

array([[472019,   2375],
       [  2038,  21689]], dtype=int64)

In [20]:
sum(np.array(gt)) * 5

array([118635], dtype=int64)